[tool.poetry]
name = "fish-text-html"
version = "0.1.0"
description = ""
authors = ["Baichik <zhumabek_uulu_b@iuca.kg>"]

[tool.poetry.dependencies]
python = "^3.7"
flask = "^2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
